export type DriveBackup = { id:string; name:string; createdTime:string; studentCount:number; classCount:number }
const DRIVE='https://www.googleapis.com/drive/v3', UPLOAD='https://www.googleapis.com/upload/drive/v3/files'
const FOLDER='Driving Attendance', MIME='application/json'
const clientId=import.meta.env.VITE_GOOGLE_CLIENT_ID as string|undefined
let token:string|undefined
let tokenExpires=0
export const googleConfigured=Boolean(clientId)
export const savedGoogleEmail=()=>localStorage.getItem('attendance.google.email')||''
export const clearGoogleAccount=()=>{localStorage.removeItem('attendance.google.email');localStorage.removeItem('attendance.google.folder');token=undefined;tokenExpires=0}
export function connectGoogle():Promise<{email:string}> { return new Promise((resolve,reject)=>{if(!clientId)return reject(new Error('Google Client ID is not configured. Add VITE_GOOGLE_CLIENT_ID to the deployment environment.'));if(!window.google)return reject(new Error('Google sign-in is still loading. Please try again.'));const client=window.google.accounts.oauth2.initTokenClient({client_id:clientId,scope:'https://www.googleapis.com/auth/drive.file https://www.googleapis.com/auth/userinfo.email',callback:async r=>{if(!r.access_token)return reject(new Error(r.error_description||'Google connection failed.'));token=r.access_token;tokenExpires=Date.now()+(r.expires_in||3600)*1000-60000;try{const u=await api<{email:string}>('https://www.googleapis.com/oauth2/v3/userinfo');localStorage.setItem('attendance.google.email',u.email);resolve({email:u.email})}catch(e){reject(e)}},error_callback:()=>reject(new Error('Google connection failed. Please try connecting again.'))});client.requestAccessToken({prompt:savedGoogleEmail()?'':'consent'})}) }
async function api<T>(url:string,init:RequestInit={}){if(!token||Date.now()>tokenExpires)throw new Error('AUTH_REQUIRED');const r=await fetch(url,{...init,headers:{Authorization:`Bearer ${token}`,...(init.headers||{})}});if(r.status===401)throw new Error('AUTH_REQUIRED');if(!r.ok)throw new Error(`DRIVE_${r.status}`);return r.status===204?undefined as T:r.json() as Promise<T>}
async function ensureToken(){if(token&&Date.now()<tokenExpires)return;if(!clientId||!window.google)throw new Error('AUTH_REQUIRED');await connectGoogle()}
async function folderId(){const saved=localStorage.getItem('attendance.google.folder');if(saved)return saved;await ensureToken();const q=encodeURIComponent(`name='${FOLDER}' and mimeType='application/vnd.google-apps.folder' and trashed=false`);const found=await api<{files:{id:string}[]}>(`${DRIVE}/files?q=${q}&spaces=drive&fields=files(id)&pageSize=1`);if(found.files[0]?.id){localStorage.setItem('attendance.google.folder',found.files[0].id);return found.files[0].id}const made=await api<{id:string}>(`${DRIVE}/files`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:FOLDER,mimeType:'application/vnd.google-apps.folder'})});localStorage.setItem('attendance.google.folder',made.id);return made.id}
const makeName=()=>{const d=new Date();const p=(n:number)=>String(n).padStart(2,'0');return `attendance-backup-${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())}-${p(d.getHours())}${p(d.getMinutes())}${p(d.getSeconds())}.json`}
export async function uploadBackup(data:unknown){await ensureToken();const parent=await folderId();const name=makeName();const body=JSON.stringify(data);const boundary='attendance_boundary';const multipart=`--${boundary}\r\nContent-Type: application/json; charset=UTF-8\r\n\r\n${JSON.stringify({name,parents:[parent],mimeType:MIME})}\r\n--${boundary}\r\nContent-Type: ${MIME}\r\n\r\n${body}\r\n--${boundary}--`;return api<{id:string;name:string}>(`${UPLOAD}?uploadType=multipart&fields=id,name`,{method:'POST',headers:{'Content-Type':`multipart/related; boundary=${boundary}`},body:multipart})}
export async function listBackups(){await ensureToken();const parent=await folderId();const q=encodeURIComponent(`'${parent}' in parents and mimeType='${MIME}' and trashed=false`);const result=await api<{files:{id:string;name:string;createdTime:string}[]}>(`${DRIVE}/files?q=${q}&orderBy=createdTime desc&fields=files(id,name,createdTime)&pageSize=100`);const backups:DriveBackup[]=[];for(const f of result.files){try{const data=await downloadBackup(f.id);backups.push({...f,studentCount:data.students?.length||0,classCount:data.attendance?.length||0})}catch{}}return backups}
export async function downloadBackup(id:string){await ensureToken();return api<any>(`${DRIVE}/files/${id}?alt=media`)}
