import { getSetting, setSetting } from './db/settings'
export type DriveBackup={id:string;name:string;createdTime:string;studentCount:number;classCount:number}
const DRIVE='https://www.googleapis.com/drive/v3',UPLOAD='https://www.googleapis.com/upload/drive/v3/files',FOLDER='Attendance Backups',clientId=import.meta.env.VITE_GOOGLE_CLIENT_ID as string|undefined
let token:string|undefined,tokenExpires=0
export const googleConfigured=Boolean(clientId)
export const savedGoogleEmail=()=>localStorage.getItem('attendance.google.email')||''
export const clearGoogleAccount=()=>{localStorage.removeItem('attendance.google.email');token=undefined;tokenExpires=0}
export function connectGoogle():Promise<{email:string}>{return new Promise((resolve,reject)=>{if(!clientId)return reject(new Error('Google Client ID is not configured.'));if(!window.google)return reject(new Error('Google Drive authorization is still loading.'));const client=window.google.accounts.oauth2.initTokenClient({client_id:clientId,scope:'https://www.googleapis.com/auth/drive.file',callback:r=>{if(!r.access_token){reject(new Error(r.error_description||'Google connection failed.'));return}token=r.access_token;tokenExpires=Date.now()+(r.expires_in||3600)*1000-60000;const email=savedGoogleEmail()||'Connected to Google Drive';localStorage.setItem('attendance.google.email',email);resolve({email})},error_callback:()=>reject(new Error('Google connection failed. Please try again.'))});client.requestAccessToken({prompt:token?'':'consent'})})}
async function api<T>(url:string,init:RequestInit={},raw=false):Promise<T>{if(!token||Date.now()>tokenExpires)throw new Error('AUTH_REQUIRED');const r=await fetch(url,{...init,headers:{Authorization:`Bearer ${token}`,...(init.headers||{})}});if(r.status===401)throw new Error('AUTH_REQUIRED');if(!r.ok)throw new Error(`DRIVE_${r.status}`);return(raw?r.blob():r.json())as Promise<T>}
async function ensureToken(){if(!token||Date.now()>tokenExpires)await connectGoogle()}
async function folderId(){const saved=await getSetting<string>('googleFolderId');if(saved)return saved;await ensureToken();const q=encodeURIComponent(`name='${FOLDER}' and mimeType='application/vnd.google-apps.folder' and trashed=false`);const found=await api<{files:{id:string}[]}>(`${DRIVE}/files?q=${q}&spaces=drive&fields=files(id)&pageSize=1`);const id=found.files[0]?.id||(await api<{id:string}>(DRIVE+'/files',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:FOLDER,mimeType:'application/vnd.google-apps.folder'})})).id;await setSetting('googleFolderId',id);return id}
const name=()=>{const d=new Date(),p=(n:number)=>String(n).padStart(2,'0');return `attendance-backup-${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())}-${p(d.getHours())}${p(d.getMinutes())}${p(d.getSeconds())}.json.gz`}
export async function uploadBackup(file:Blob,counts:{students:number;attendance:number}){await ensureToken();const parent=await folderId(),boundary='attendance_boundary';const head=`--${boundary}\r\nContent-Type: application/json; charset=UTF-8\r\n\r\n${JSON.stringify({name:name(),parents:[parent],mimeType:'application/gzip',appProperties:{students:String(counts.students),attendance:String(counts.attendance)}})}\r\n--${boundary}\r\nContent-Type: application/gzip\r\n\r\n`;const body=new Blob([head,file,`\r\n--${boundary}--`],{type:`multipart/related; boundary=${boundary}`});return api<{id:string}>(`${UPLOAD}?uploadType=multipart&fields=id`,{method:'POST',headers:{'Content-Type':body.type},body})}
export async function listBackups():Promise<DriveBackup[]>{await ensureToken();const parent=await folderId();const q=encodeURIComponent(`'${parent}' in parents and trashed=false`);const result=await api<{files:Array<{id:string;name:string;createdTime:string;appProperties?:Record<string,string>}>}>(`${DRIVE}/files?q=${q}&orderBy=createdTime desc&fields=files(id,name,createdTime,appProperties)&pageSize=100`);return result.files.filter(f=>f.name.endsWith('.json.gz')).map(f=>({...f,studentCount:Number(f.appProperties?.students||0),classCount:Number(f.appProperties?.attendance||0)}))}
export async function downloadBackup(id:string){await ensureToken();return api<Blob>(`${DRIVE}/files/${id}?alt=media`,{},true)}
