import { useEffect, useMemo, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { ArrowLeft, Check, ChevronRight, Cloud, Download, Edit3, History, Plus, Search, Settings, Trash2, Upload, UserRound, X } from 'lucide-react'
import './styles.css'
import './overrides.css'
import './branding-overrides.css'
import { clearGoogleAccount, connectGoogle, downloadBackup, googleConfigured, listBackups, savedGoogleEmail, uploadBackup, type DriveBackup } from './googleDrive'

type Student = { id:string; name:string; phone:string; total:number; archived:boolean; createdAt:string }
type Attendance = { id:string; studentId:string; number:number; completedAt:string }
const DB='attendance-ledger', STORE='records'
let driveActions:{email:string;configured:boolean;busy:boolean;connect:()=>void;disconnect:()=>void;backup:()=>void;restore:()=>void;csv:()=>void;students:{id:string;name:string;count:number}[];deleteStudent:(id:string)=>void}={email:'',configured:false,busy:false,connect:()=>{},disconnect:()=>{},backup:()=>{},restore:()=>{},csv:()=>{},students:[],deleteStudent:()=>{}}
const uid=()=>crypto.randomUUID?.() ?? `${Date.now()}-${Math.random()}`
const dateLabel=(d:string)=>new Intl.DateTimeFormat('en-US',{month:'short',day:'2-digit',year:'numeric'}).format(new Date(d))
const timeLabel=(d:string)=>new Intl.DateTimeFormat('en-US',{hour:'numeric',minute:'2-digit'}).format(new Date(d))

function openDb(){ return new Promise<IDBDatabase>((resolve,reject)=>{ const r=indexedDB.open(DB,1); r.onupgradeneeded=()=>{const db=r.result; db.createObjectStore(STORE,{keyPath:'id'})}; r.onsuccess=()=>resolve(r.result); r.onerror=()=>reject(r.error) }) }
async function readAll<T>(kind:'students'|'attendance'){ const db=await openDb(); return new Promise<T[]>((resolve,reject)=>{const q=db.transaction(STORE,'readonly').objectStore(STORE).getAll(); q.onsuccess=()=>resolve((q.result as any[]).filter(x=>x.kind===kind)); q.onerror=()=>reject(q.error)}) }
async function putAll(items:any[]){const db=await openDb(); return new Promise<void>((resolve,reject)=>{const t=db.transaction(STORE,'readwrite'); items.forEach(x=>t.objectStore(STORE).put(x)); t.oncomplete=()=>resolve(); t.onerror=()=>reject(t.error)})}
async function removeOne(id:string){const db=await openDb(); db.transaction(STORE,'readwrite').objectStore(STORE).delete(id)}
async function replaceAll(items:any[]){const db=await openDb(); return new Promise<void>((resolve,reject)=>{const t=db.transaction(STORE,'readwrite'),store=t.objectStore(STORE);store.clear();items.forEach(x=>store.put(x));t.oncomplete=()=>resolve();t.onerror=()=>reject(t.error)})}
const seedStudents:Student[]=[{id:'rahul',name:'Rahul Kumar',phone:'98765 43210',total:20,archived:false,createdAt:'2026-08-01'},{id:'ahmed',name:'Ahmed Khan',phone:'99887 76655',total:20,archived:false,createdAt:'2026-08-01'},{id:'sameer',name:'Sameer Ali',phone:'90000 22110',total:20,archived:false,createdAt:'2026-08-01'},{id:'priya',name:'Priya Shah',phone:'',total:20,archived:true,createdAt:'2026-07-01'}]
const seedAttendance:Attendance[]=[
 ...[...Array(13)].map((_,i)=>({id:`r${i}`,studentId:'rahul',number:i+1,completedAt:`2026-08-${String(3+i*2).padStart(2,'0')}T10:30:00`})),
 ...[...Array(8)].map((_,i)=>({id:`a${i}`,studentId:'ahmed',number:i+1,completedAt:`2026-08-${String(4+i*2).padStart(2,'0')}T11:30:00`})),
 ...[...Array(19)].map((_,i)=>({id:`s${i}`,studentId:'sameer',number:i+1,completedAt:`2026-08-${String(2+i).padStart(2,'0')}T09:30:00`})),
 ...[...Array(20)].map((_,i)=>({id:`p${i}`,studentId:'priya',number:i+1,completedAt:`2026-07-${String(2+i).padStart(2,'0')}T09:30:00`}))
]

function App(){
 const [students,setStudents]=useState<Student[]>([]),[attendance,setAttendance]=useState<Attendance[]>([]),[tab,setTab]=useState<'students'|'completed'|'settings'>('students'),[query,setQuery]=useState(''),[selected,setSelected]=useState<string|null>(null),[modal,setModal]=useState<'add'|'edit'|null>(null),[toast,setToast]=useState<string|null>(null),[last,setLast]=useState<Attendance|null>(null),[form,setForm]=useState({name:'',phone:'',total:'20'}),[backup,setBackup]=useState('Not backed up yet'),[googleEmail,setGoogleEmail]=useState(savedGoogleEmail()),[driveBackups,setDriveBackups]=useState<DriveBackup[]>([]),[restoreOpen,setRestoreOpen]=useState(false),[restoreSelected,setRestoreSelected]=useState<string|null>(null),[busy,setBusy]=useState(false)
 useEffect(()=>{(async()=>{let s=await readAll<Student>('students'),a=await readAll<Attendance>('attendance'); if(!s.length){s=seedStudents;a=seedAttendance;await putAll([...s.map(x=>({...x,kind:'students'})),...a.map(x=>({...x,kind:'attendance'}))])} setStudents(s);setAttendance(a)})()},[])
 useEffect(()=>{if(!toast)return;const t=setTimeout(()=>setToast(null),3500);return()=>clearTimeout(t)},[toast])
 const counts=useMemo(()=>Object.fromEntries(students.map(s=>[s.id,attendance.filter(a=>a.studentId===s.id).length])),[students,attendance])
 const visible=students.filter(s=>tab==='completed'?counts[s.id]>=s.total:tab==='students'&&!s.archived&&counts[s.id]<s.total).filter(s=>`${s.name} ${s.phone}`.toLowerCase().includes(query.toLowerCase()))
 const current=selected?students.find(s=>s.id===selected):null
 const save=async(s:Student)=>{await putAll([{...s,kind:'students'}]);setStudents(v=>v.some(x=>x.id===s.id)?v.map(x=>x.id===s.id?s:x):[...v,s])}
 const complete=async(s:Student)=>{const n=(counts[s.id]||0)+1;if(n>s.total)return;const a={id:uid(),studentId:s.id,number:n,completedAt:new Date().toISOString()};try{await putAll([{...a,kind:'attendance'}]);setAttendance(v=>[...v,a]);setLast(a);setToast(`Class #${n} completed for ${s.name}`)}catch{setToast("Couldn't save attendance. Your existing data is safe.")}}
 const undo=async()=>{if(!last)return;await removeOne(last.id);setAttendance(v=>v.filter(a=>a.id!==last.id));setToast('Last class undone');setLast(null)}
 const submit=async(e:React.FormEvent)=>{e.preventDefault();if(!form.name.trim())return;const s:Student={id:modal==='edit'&&current?current.id:uid(),name:form.name.trim(),phone:form.phone.trim(),total:Math.max(1,Number(form.total)||20),archived:false,createdAt:current?.createdAt||new Date().toISOString()};await save(s);setModal(null);setToast(modal==='add'?'Student added':'Student updated')}
 const exportData=async()=>{const data={version:1,created_at:new Date().toISOString(),students,attendance};const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`backup-${new Date().toISOString().slice(0,10)}.json`;a.click();setBackup(`${dateLabel(new Date().toISOString())}, ${timeLabel(new Date().toISOString())}`);setToast('Backup downloaded')}
 const exportCsv=async()=>{try{const escape=(value:unknown)=>{const text=String(value??'');return /[",\n\r]/.test(text)?`"${text.replace(/"/g,'""')}"`:text};const localDate=(d:Date)=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;const rows=[['Student Name','Phone','Completed Classes','Total Classes','Remaining Classes','Progress','Last Class Date','Status'],...students.map(s=>{const records=attendance.filter(a=>a.studentId===s.id);const count=records.length;const last=records.slice().sort((a,b)=>new Date(b.completedAt).getTime()-new Date(a.completedAt).getTime())[0];const pct=Math.min(100,Math.round(count/s.total*100));return [s.name,s.phone,count,s.total,Math.max(0,s.total-count),`${pct}%`,last?localDate(new Date(last.completedAt)):'',count>=s.total?'Completed':'Active']})];const csv='\ufeff'+rows.map(row=>row.map(escape).join(',')).join('\r\n')+'\r\n';const file=new File([csv],`driving-attendance-${localDate(new Date())}.csv`,{type:'text/csv;charset=utf-8'});if(navigator.share&&(!navigator.canShare||navigator.canShare({files:[file]}))){try{await navigator.share({files:[file],title:'Driving Attendance'})}catch(e){if(e instanceof DOMException&&e.name==='AbortError')return;throw e}}else{const a=document.createElement('a');a.href=URL.createObjectURL(file);a.download=file.name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}setToast('Attendance CSV ready to share')}catch{setToast("Couldn't create the CSV file. Your attendance data is safe.")}}
 const backupToDrive=async()=>{if(!navigator.onLine){setToast('No internet connection. Connect to back up to Google Drive.');return}setBusy(true);try{if(!googleEmail){const g=await connectGoogle();setGoogleEmail(g.email)}await uploadBackup({version:1,created_at:new Date().toISOString(),students,attendance});setBackup(`${dateLabel(new Date().toISOString())}, ${timeLabel(new Date().toISOString())}`);setToast('Backup successful')}catch(e){setToast(e instanceof Error&&e.message.includes('Client ID')?'Add VITE_GOOGLE_CLIENT_ID to connect Google.':'Backup failed. Your local attendance data is safe.')}finally{setBusy(false)}}
 const openRestore=async()=>{if(!navigator.onLine){setToast('No internet connection. Connect to restore from Google Drive.');return}setBusy(true);try{if(!googleEmail){const g=await connectGoogle();setGoogleEmail(g.email)}const found=await listBackups();if(!found.length){setToast('No attendance backups were found in this Google account.');return}setDriveBackups(found);const choice=window.prompt(`Available backups:\n${found.map((b,i)=>`${i+1}. ${dateLabel(b.createdTime)} · ${b.studentCount} students · ${b.classCount} classes`).join('\n')}\n\nEnter a backup number to restore:`,'1');const index=Number(choice)-1;if(!Number.isInteger(index)||!found[index])return;const selected=found[index];if(!window.confirm(`Restore backup from ${dateLabel(selected.createdTime)}?\n\nThis will replace the current data on this device.`))return;const data=await downloadBackup(selected.id);if(data.version!==1||!Array.isArray(data.students)||!Array.isArray(data.attendance))throw new Error();await replaceAll([...data.students.map((x:Student)=>({...x,kind:'students'})),...data.attendance.map((x:Attendance)=>({...x,kind:'attendance'}))]);setStudents(data.students);setAttendance(data.attendance);setToast('Backup restored')}catch{setToast('Restore failed. Your current local data has not been changed.')}finally{setBusy(false)}}
 const restoreFromDrive=async()=>{if(!restoreSelected)return;setBusy(true);try{const data=await downloadBackup(restoreSelected);if(data.version!==1||!Array.isArray(data.students)||!Array.isArray(data.attendance))throw new Error();await replaceAll([...data.students.map((x:Student)=>({...x,kind:'students'})),...data.attendance.map((x:Attendance)=>({...x,kind:'attendance'}))]);setStudents(data.students);setAttendance(data.attendance);setRestoreOpen(false);setToast('Backup restored')}catch{setToast('Restore failed. Your current local data has not been changed.')}finally{setBusy(false)}}
 const disconnect=()=>{clearGoogleAccount();setGoogleEmail('');setToast('Disconnected. Local attendance data remains safely on this device.')}
 const deleteStudent=async(id:string)=>{const student=students.find(s=>s.id===id);if(!student||!window.confirm(`Delete ${student.name}?\n\nThis will permanently remove the student and all ${counts[id]||0} attendance records from this device.`))return;await replaceAll([...students.filter(s=>s.id!==id).map(x=>({...x,kind:'students'})),...attendance.filter(a=>a.studentId!==id).map(x=>({...x,kind:'attendance'}))]);setStudents(v=>v.filter(s=>s.id!==id));setAttendance(v=>v.filter(a=>a.studentId!==id));setToast(`${student.name} deleted`)}
 driveActions={email:googleEmail,configured:googleConfigured,busy,connect:async()=>{try{const g=await connectGoogle();setGoogleEmail(g.email);setToast('Google account connected')}catch(e){setToast(e instanceof Error?e.message:'Google connection failed.')}},disconnect,backup:backupToDrive,restore:openRestore,csv:exportCsv,students:students.map(s=>({id:s.id,name:s.name,count:counts[s.id]||0})),deleteStudent}
 return <div className="app"><header><div className="eyebrow"><span className="mark">A</span><span>DRIVING INSTRUCTOR</span><span className="live"><i/> LOCAL ONLY</span></div><div className="headrow"><div><h1>{tab==='settings'?'Settings':current?current.name:'Attendance'}</h1><p>{current?'Progress & class history':tab==='completed'?'Students who finished their package':'Your digital attendance book'}</p></div>{current&&<button className="iconBtn" onClick={()=>setSelected(null)} aria-label="Back"><ArrowLeft size={20}/></button>}</div></header>
 {tab!=='settings'&&!current&&<main><div className="search"><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search by name or phone"/><kbd>⌘ K</kbd></div><button className="addBtn" onClick={()=>{setForm({name:'',phone:'',total:'20'});setModal('add')}}><Plus size={18}/> Add student</button><div className="sectionLabel"><span>{tab==='completed'?'COMPLETED':'ACTIVE STUDENTS'}</span><b>{visible.length}</b></div>{!visible.length?<div className="empty"><UserRound size={32}/><h2>{query?'No students found':tab==='completed'?'No completed students yet':'No active students'}</h2><p>{query?'Try a different name or phone number.':'Add your first student to get started.'}</p></div>:<div className="list">{visible.map(s=><StudentRow key={s.id} s={s} count={counts[s.id]||0} onOpen={()=>setSelected(s.id)} onComplete={()=>complete(s)}/>)}</div>}</main>}
 {current&&<Detail s={current} count={counts[current.id]||0} history={attendance.filter(a=>a.studentId===current.id).sort((a,b)=>b.number-a.number)} onComplete={()=>complete(current)} onEdit={()=>{setForm({name:current.name,phone:current.phone,total:String(current.total)});setModal('edit')}} onDelete={async a=>{await removeOne(a.id);setAttendance(v=>v.filter(x=>x.id!==a.id));setToast('Attendance record deleted')}}/>}
 {tab==='settings'&&<SettingsView backup={backup} onBackup={exportData}/>}<nav><button className={tab==='students'?'active':''} onClick={()=>{setTab('students');setSelected(null)}}><UserRound size={19}/>Students</button><button className={tab==='completed'?'active':''} onClick={()=>{setTab('completed');setSelected(null)}}><Check size={19}/>Completed</button><button className={tab==='settings'?'active':''} onClick={()=>{setTab('settings');setSelected(null)}}><Settings size={19}/>Settings</button></nav>{toast&&<div className="toast">{toast}{last&&<button onClick={undo}>UNDO</button>}</div>}{modal&&<div className="scrim"><form className="modal" onSubmit={submit}><div className="modalTop"><div><span className="eyebrow">STUDENT DETAILS</span><h2>{modal==='add'?'Add student':'Edit student'}</h2></div><button type="button" className="iconBtn" onClick={()=>setModal(null)}><X size={19}/></button></div><label>Name<input autoFocus value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="e.g. Rahul Kumar"/></label><label>Phone <small>optional</small><input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})} placeholder="e.g. 98765 43210"/></label><label>Total classes<input type="number" min="1" value={form.total} onChange={e=>setForm({...form,total:e.target.value})}/></label><button className="primary" type="submit">{modal==='add'?'Add student':'Save changes'} <ChevronRight size={17}/></button></form></div>}</div>
}
function StudentRow({s,count,onOpen,onComplete}:{s:Student;count:number;onOpen:()=>void;onComplete:()=>void}){const pct=Math.min(100,Math.round(count/s.total*100));return <article className="studentRow"><button className="studentMain" onClick={onOpen}><div className="avatar">{s.name.split(' ').map(x=>x[0]).join('').slice(0,2)}</div><div><h2>{s.name}</h2><p>{count} <span>/ {s.total} classes</span></p></div><ChevronRight className="chev" size={18}/></button><div className="progress"><span style={{width:`${pct}%`}}/></div><div className="rowBottom"><span>{s.total-count} remaining <em>{pct}%</em></span><button className="plus" onClick={onComplete}><Plus size={20}/>1</button></div></article>}
function Detail({s,count,history,onComplete,onEdit,onDelete}:{s:Student;count:number;history:Attendance[];onComplete:()=>void;onEdit:()=>void;onDelete:(a:Attendance)=>void}){const pct=Math.min(100,Math.round(count/s.total*100));return <main className="detail"><div className="detailCard"><div className="detailMeta"><div className="avatar big">{s.name.split(' ').map(x=>x[0]).join('').slice(0,2)}</div><button className="edit" onClick={onEdit}><Edit3 size={15}/> Edit</button></div><h2>{s.name}</h2><p className="phone">{s.phone||'No phone number added'}</p><div className="bigStat"><strong>{count}</strong><span>/ {s.total} classes</span><b>{pct}%</b></div><div className="progress"><span style={{width:`${pct}%`}}/></div>{count>=s.total?<div className="complete"><Check size={18}/> Course completed</div>:<button className="primary completeBtn" onClick={onComplete}><Plus size={20}/> Complete class</button>}</div><div className="historyHead"><span>CLASS HISTORY</span><b>{history.length} records</b></div>{history.length?<div className="history">{history.map(a=><div className="historyRow" key={a.id}><div className="historyIcon"><History size={17}/></div><div><strong>Class #{a.number}</strong><p>{dateLabel(a.completedAt)} <span>· {timeLabel(a.completedAt)}</span></p></div><button onClick={()=>onDelete(a)} aria-label="Delete record"><Trash2 size={17}/></button></div>)}</div>:<div className="empty mini"><History size={25}/><p>No classes recorded yet.</p></div>}</main>}
function SettingsView({backup,onBackup}:{backup:string;onBackup:()=>void}){const [manageOpen,setManageOpen]=useState(false);return <main className="settingsPage"><div className="settingIntro"><div className="settingIcon"><Cloud size={24}/></div><div><h2>Your data stays yours.</h2><p>Attendance is stored on this device. Google Drive is only used when you explicitly back up or restore.</p></div></div><section className="settingSection"><div className="sectionLabel"><span>GOOGLE ACCOUNT</span></div><div className="settingCard"><div><strong>{driveActions.email?'✓ Connected':'Not connected'}</strong><p>{driveActions.email||'Connect Google to use Drive backup.'}</p></div>{driveActions.email?<button className="outline" onClick={driveActions.disconnect}>Disconnect</button>:<button className="outline" disabled={!driveActions.configured} onClick={driveActions.connect}>Connect Google</button>}</div>{!driveActions.configured&&<p className="configNote">Google Drive needs a configured OAuth client ID before it can connect.</p>}</section><section className="settingSection"><div className="sectionLabel"><span>DATA</span></div><div className="settingCard"><div><strong>Last backup</strong><p>{backup}</p></div><button className="outline" disabled={driveActions.busy} onClick={driveActions.backup}><Cloud size={17}/> {driveActions.busy?'Working…':'Backup to Drive'}</button></div><div className="settingCard"><div><strong>Restore from Google Drive</strong><p>Choose a previous attendance book backup.</p></div><button className="outline" disabled={driveActions.busy} onClick={driveActions.restore}><Upload size={17}/> Restore</button></div><div className="settingCard"><div><strong>Export Attendance CSV</strong><p>One row per student, ready to share on iPhone.</p></div><button className="outline" onClick={driveActions.csv}><Download size={17}/> Export CSV</button></div><div className="settingCard muted"><div><strong>Full backup JSON</strong><p>Complete local data for manual safekeeping.</p></div><button className="outline" onClick={onBackup}><Download size={17}/> Export JSON</button></div></section><section className="settingSection"><div className="sectionLabel"><span>MANAGE STUDENTS</span></div><div className="dangerCard"><button className={`manageToggle${manageOpen?' open':''}`} onClick={()=>setManageOpen(v=>!v)}><span>Manage students</span><ChevronRight size={18}/></button>{manageOpen&&<><p>Deleting a student also deletes their attendance history.</p>{driveActions.students.map(s=><div className="manageRow" key={s.id}><div><strong>{s.name}</strong><span>{s.count} completed classes</span></div><button className="deleteBtn" onClick={()=>driveActions.deleteStudent(s.id)}><Trash2 size={16}/> Delete</button></div>)}</>}</div></section><section className="about"><span className="mark">A</span><p><strong>EverGreen Driving School</strong><br/>A quiet, reliable book for the road.</p></section></main>}
export default App

createRoot(document.getElementById('root')!).render(<App />)
if ('serviceWorker' in navigator) navigator.serviceWorker.register(`${import.meta.env.BASE_URL}sw.js`).catch(() => {})
